# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.FileField(blank=True, upload_to='pic_folder/'),
        ),
    ]
